moviescatalog/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
  path('', views.home, name='home'),
]

moviescatalog/moviescatalog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
  path('admin/', admin.site.urls),
  path('users/', include('users.urls')),
  path('', include('home.urls')),
  path('watched/', include('watched.urls')),
  path('search/', include('search.urls')),
  path('movie/', include('movie.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moviescatalog/users/urls.py
from django.urls import path
from .views import home, login_view, register_view, logout_view, change_password, perfil, minhas_avaliacoes

app_name = "users"

urlpatterns = [
  path('', home, name='home'),
  path("perfil/", perfil, name="perfil"),
  path("avaliacoes/", minhas_avaliacoes, name="minhas_avaliacoes"),
  path('login/', login_view, name='login'),
  path('register/', register_view, name='register'),
  path('password-reset/', change_password, name='change_password'),
  path('logout/', logout_view, name='logout'),
]

moviescatalog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}Filmes | Catálogo de Filmes {% endblock %}</title>

    <!-- CSS global -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/global.css' %}" />
    {% block style %}{% endblock %}

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Italianno&display=swap" rel="stylesheet"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Keania+One&family=Kenia&display=swap" rel="stylesheet">

  </head>
  <body>
    {% block content %}{% endblock %}

    <script src="{% static 'js/global.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    {% block js %}{% endblock %}
  </body>
</html>

moviescatalog/templates/footer.html
<div class="bottom-nav">
  <a href="{% url 'users:perfil' %}" class="nav-item {% if request.path == '/users/perfil/' %}active{% endif %}">
    <div class="nav-icon">
      <i class="bi bi-person"></i>
    </div>
    <div>Perfil</div>
  </a>
  <a href="{% url 'home:home' %}" class="nav-item {% if request.path == '/' %}active{% endif %}">
    <div class="nav-icon">
      <i class="bi bi-house"></i>
    </div>
    <div>Painel</div>
  </a>
  <a href="{% url 'users:minhas_avaliacoes' %}" class="nav-item {% if request.path == '/users/avaliacoes/' %}active{% endif %}">
    <div class="nav-icon">
      <i class="bi bi-chat-dots"></i>
    </div>
    <div>Avaliações</div>
  </a>
</div>

moviescatalog/templates/header.html
{% load static %}
<header class="header">
  <div class="menu-container">
    
    <div class="logo">
      <a href="{% url 'home:home' %}"><h1>Film+</h1></a>
    </div>

    <div class="search-container">
      <form method="get" action="{% url 'movie_search' %}" class="search-form-header">
        <input type="text" name="query" value="{{ request.GET.query }}" placeholder="Buscar filmes..." class="search-input" />
        <button type="submit" class="search-button">
          <i class="bi bi-search"></i>
        </button>
      </form>
    </div>
  </div>
</header>